unit TestfrmPrincipal;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Windows, Forms, Dialogs, Controls, frmPrincipal, Classes, SysUtils,
  Variants, Graphics, Messages;

type
  // Test methods for class TForm2

  TestTForm2 = class(TTestCase)
  strict private
    FForm2: TForm2;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure Testsoma;
    procedure TestSubtracao;
    procedure TestDivisao;
  end;

implementation

procedure TestTForm2.SetUp;
begin
end;

procedure TestTForm2.TearDown;
begin
  FForm2.Free;
  FForm2 := nil;
end;

procedure TestTForm2.TestDivisao;
var
  x:double;
  y:double;
  z:double;
begin
  x := 10;
  y := 3;
  z := FForm2.divisao(x,y);

  CheckEquals(3.33,z);
end;

procedure TestTForm2.Testsoma;
var
  ReturnValue: Integer;
  b: Integer;
  a: Integer;
begin
  a := 3;
  b := 2;
  ReturnValue := FForm2.soma(a, b);

  CheckEquals(5,ReturnValue);
    Status('FUNCIONOU SOMA');
end;
procedure TestTForm2.TestSubtracao;
var
  ReturnValue: Integer;
  b: Integer;
  a: Integer;
begin
  a := 3;
  b := 2;
  ReturnValue := FForm2.subtracao(a, b);

  CheckEquals(1,ReturnValue);
  Status('FUNCIONOU SUBTRAÇÃO');
end;
initialization
  RegisterTest(TestTForm2.Suite);
end.

